import csv
import html
import json
import re

# Comprehensive canonical translation dictionary
TRANSLATIONS = {
    # 1. Single-word actions, buttons & status
    "Abbrechen": "Cancelar",
    "Speichern": "Salvar",
    "Speichern unter...": "Salvar como...",
    "Schließen": "Fechar",
    "Schliessen": "Fechar",
    "Schließen ": "Fechar ",
    "Suchen": "Pesquisar",
    "Suche": "Pesquisa",
    "Löschen": "Excluir",
    "löschen": "Excluir",
    "Entfernen": "Remover",
    "entfernen": "Remover",
    "Hinzufügen": "Adicionar",
    "hinzufügen": "Adicionar",
    "Neu": "Novo",
    "Neuer": "Novo",
    "Neues": "Novo",
    "Neue": "Nova",
    "neue": "nova",
    "neues": "novo",
    "neuer": "novo",
    "Bearbeiten": "Editar",
    "bearbeiten": "Editar",
    "Drucken": "Imprimir",
    "drucken": "Imprimir",
    "Druckvorschau": "Visualizar Impressão",
    "Exportieren": "Exportar",
    "Importieren": "Importar",
    "Aktualisieren": "Atualizar",
    "Zurück": "Voltar",
    "Weiter": "Avançar",
    "Fertig": "Concluir",
    "Übernehmen": "Aplicar",
    "übernehmen": "Aplicar",
    "Ansicht": "Exibir",
    "Öffnen": "Abrir",
    "öffnen": "Abrir",
    "öffnen...": "Abrir...",
    "öffnen mit...": "Abrir com...",
    "Auswählen": "Selecionar",
    "auswählen": "Selecionar",
    "Auswahl": "Seleção",
    "Bestätigen": "Confirmar",
    "Bestätigung": "Confirmação",
    "Senden": "Enviar",
    "senden": "Enviar",
    "Signieren": "Assinar digitalmente",
    "Scannen": "Digitalizar",
    "Vorschau": "Visualização",
    "Anlegen": "Criar",
    "anlegen": "Criar",
    "Erstellen": "Criar",
    "erstellen": "Criar",
    "Duplizieren": "Duplicar",
    "duplizieren": "Duplicar",
    "Umbenennen": "Renomear",
    "umbenennen": "Renomear",
    "Kopieren": "Copiar",
    "kopieren": "Copiar",
    "Verschieben": "Mover",
    "verschieben": "Mover",
    "Verbinden": "Conectar",
    "Trennen": "Desconectar",
    "Prüfen": "Verificar",
    "Hilfe": "Ajuda",
    "Optionen": "Opções",
    "Einstellungen": "Configurações",
    "Ja": "Sim",
    "Nein": "Não",
    "Fehler": "Erro",
    "Erfolg": "Sucesso",
    "Erfolgreich": "Sucesso",
    "Warnung": "Aviso",
    "Hinweis": "Aviso",
    "Achtung": "Atenção",
    "Information": "Informação",
    "Details": "Detalhes",
    "Alles auswählen": "Selecionar tudo",
    "Auswahl aufheben": "Desmarcar seleção",
    "Heute": "Hoje",
    "Morgen": "Amanhã",
    "Gestern": "Ontem",
    "Nächste Woche": "Próxima semana",
    "Übermorgen": "Depois de amanhã",
    "In 1 Woche": "Em 1 semana",
    "In 2 Wochen": "Em 2 semanas",
    "In 1 Monat": "Em 1 mês",
    "Komprimieren": "Compactar",

    # 2. Entities & Field Labels
    "Mandant": "Cliente",
    "Mandanten": "Clientes",
    "Gegner": "Parte Contrária",
    "Dritte": "Terceiros",
    "Akte": "Processo",
    "Akten": "Processos",
    "Akte:": "Processo:",
    "Akten:": "Processos:",
    "Aktenzeichen": "Número do Processo",
    "Aktenzeichen:": "Número do Processo:",
    "Aktennotiz": "Anotação do Processo",
    "Aktenkonto": "Conta do Processo",
    "Dokument": "Documento",
    "Dokumente": "Documentos",
    "Dokument:": "Documento:",
    "Dokumente:": "Documentos:",
    "Datei": "Arquivo",
    "Dateien": "Arquivos",
    "Datei:": "Arquivo:",
    "Dateien:": "Arquivos:",
    "Ordner": "Pasta",
    "Ordner:": "Pasta:",
    "Benutzer": "Usuário",
    "Benutzer:": "Usuário:",
    "Benutzername": "Nome de Usuário",
    "Benutzername:": "Nome de Usuário:",
    "Passwort": "Senha",
    "Passwort:": "Senha:",
    "Kennwort": "Senha",
    "Kennwort:": "Senha:",
    "root-Passwort:": "Senha de Administrador (root):",
    "Verbindung": "Conexão",
    "Termin": "Audiência / Compromisso",
    "Termine": "Compromissos",
    "Frist": "Prazo",
    "Fristen": "Prazos",
    "Wiedervorlage": "Lembrete",
    "Wiedervorlagen": "Lembretes",
    "Wiedervorlage / Frist": "Lembrete / Prazo",
    "Rechnung": "Fatura",
    "Rechnungen": "Faturas",
    "Zahlung": "Pagamento",
    "Zahlungen": "Pagamentos",
    "Zahlung:": "Pagamento:",
    "Zahlungseingang": "Recebimento",
    "Zahlungsausgang": "Pagamento Efetuado",
    "Honorar": "Honorários",
    "Vergütung": "Honorários",
    "Gericht": "Tribunal",
    "Gerichte": "Tribunais",
    "Beteiligte": "Partes Envolvidas",
    "Beteiligter": "Parte Envolvida",
    "Beteiligtentypen": "Tipos de Partes Envolvidas",
    "Rubrum": "Cabeçalho Processual",
    "Vorlage": "Modelo",
    "Vorlagen": "Modelos",
    "Vorlage:": "Modelo:",
    "Nachname": "Sobrenome",
    "Nachname:": "Sobrenome:",
    "Vorname": "Nome",
    "Vorname:": "Nome:",
    "Straße": "Endereço / Logradouro",
    "Straße:": "Endereço / Logradouro:",
    "PLZ": "CEP",
    "PLZ:": "CEP:",
    "Ort": "Cidade",
    "Ort:": "Cidade:",
    "Telefon": "Telefone",
    "Telefon:": "Telefone:",
    "Mobiltelefon": "Celular",
    "Mobiltelefon:": "Celular:",
    "Telefax": "Fax",
    "Telefax:": "Fax:",
    "E-Mail": "E-mail",
    "E-Mail:": "E-mail:",
    "Webseite": "Site",
    "Notiz": "Nota",
    "Notizen": "Notas",
    "Betreff": "Assunto",
    "Betreff:": "Assunto:",
    "An:": "Para:",
    "Kopie (CC):": "Cópia (CC):",
    "Blindkopie (BCC):": "Cópia Oculta (CCO):",
    "Posteingang": "Caixa de Entrada",
    "Postausgang": "Caixa de Saída",
    "Entwürfe": "Rascunhos",
    "Gesendet": "Enviados",
    "Papierkorb": "Lixeira",
    "Spam": "Spam",
    "Etikett": "Etiqueta",
    "Etiketten": "Etiquetas",
    "Status": "Status",
    "Status:": "Status:",
    "Beschreibung": "Descrição",
    "Beschreibung:": "Descrição:",
    "Datum": "Data",
    "Datum:": "Data:",
    "Uhrzeit": "Hora",
    "Uhrzeit:": "Hora:",
    "Betrag": "Valor",
    "Betrag:": "Valor:",
    "Saldo": "Saldo",
    "Saldo:": "Saldo:",
}

print(f"Initial translations: {len(TRANSLATIONS)}")
