import os
import sys
import json
import csv
import html
import re

# Comprehensive dictionary for all form property values and corresponding initComponents strings
FORM_TRANSLATIONS = {
    # Buttons and basic controls
    "Abbrechen": "Cancelar",
    "Speichern": "Salvar",
    "Speichern unter...": "Salvar como...",
    "Schließen": "Fechar",
    "Schliessen": "Fechar",
    "Schließen ": "Fechar ",
    "Suchen": "Pesquisar",
    "suchen": "Pesquisar",
    "Suche": "Pesquisa",
    "Löschen": "Excluir",
    "löschen": "Excluir",
    "Entfernen": "Remover",
    "entfernen": "Remover",
    "Hinzufügen": "Adicionar",
    "hinzufügen": "Adicionar",
    "Neu": "Novo",
    "Neuer": "Novo",
    "Neues": "Novo",
    "Neue": "Nova",
    "neue": "nova",
    "neues": "novo",
    "neuer": "novo",
    "Bearbeiten": "Editar",
    "bearbeiten": "Editar",
    "Drucken": "Imprimir",
    "drucken": "Imprimir",
    "Druckvorschau": "Visualizar Impressão",
    "Exportieren": "Exportar",
    "Importieren": "Importar",
    "Aktualisieren": "Atualizar",
    "Zurück": "Voltar",
    "Weiter": "Avançar",
    "Fertig": "Concluir",
    "Übernehmen": "Aplicar",
    "übernehmen": "Aplicar",
    "Ansicht": "Exibir",
    "Öffnen": "Abrir",
    "öffnen": "Abrir",
    "öffnen...": "Abrir...",
    "öffnen mit...": "Abrir com...",
    "Auswählen": "Selecionar",
    "auswählen": "Selecionar",
    "Auswahl": "Seleção",
    "Bestätigen": "Confirmar",
    "Bestätigung": "Confirmação",
    "Senden": "Enviar",
    "senden": "Enviar",
    "Signieren": "Assinar digitalmente",
    "Scannen": "Digitalizar",
    "Vorschau": "Visualização",
    "Vorschau:": "Visualização:",
    "Anlegen": "Criar",
    "anlegen": "Criar",
    "Erstellen": "Criar",
    "erstellen": "Criar",
    "Duplizieren": "Duplicar",
    "duplizieren": "Duplicar",
    "Umbenennen": "Renomear",
    "umbenennen": "Renomear",
    "Kopieren": "Copiar",
    "kopieren": "Copiar",
    "Verschieben": "Mover",
    "verschieben": "Mover",
    "Verbinden": "Conectar",
    "Trennen": "Desconectar",
    "Prüfen": "Verificar",
    "Hilfe": "Ajuda",
    "Optionen": "Opções",
    "Einstellungen": "Configurações",
    "Ja": "Sim",
    "Nein": "Não",
    "Fehler": "Erro",
    "Erfolg": "Sucesso",
    "Erfolgreich": "Sucesso",
    "Warnung": "Aviso",
    "Hinweis": "Aviso",
    "Achtung": "Atenção",
    "Information": "Informação",
    "Details": "Detalhes",
    "Alles auswählen": "Selecionar tudo",
    "Auswahl aufheben": "Desmarcar seleção",
    "Heute": "Hoje",
    "Morgen": "Amanhã",
    "Gestern": "Ontem",
    "Nächste Woche": "Próxima semana",
    "Übermorgen": "Depois de amanhã",
    "In 1 Woche": "Em 1 semana",
    "In 2 Wochen": "Em 2 semanas",
    "In 1 Monat": "Em 1 mês",
    "Komprimieren": "Compactar",
    "Komprimieren und Speichern": "Compactar e Salvar",
    "Vorschau der Komprimierung": "Visualização da compactação",
    "In Graustufen konvertieren": "Converter para escala de cinza",
    "in Schwarz/Weiß konvertieren": "Converter para preto e branco",
    "Urspr. Dateien überschreiben": "Sobrescrever arquivos originais",
    "Qualitätsstufe auswählen:": "Selecionar nível de qualidade:",
    "Doppelklick um heutiges Datum zu übernehmen": "Duplo clique para aplicar a data de hoje",
    "Text auswählen und in die Zwischenablage kopieren": "Selecionar texto e copiar para a área de transferência",
    "Chat-Historie zurücksetzen und neuen Chat beginnen": "Limpar histórico e iniciar nova conversa",
    "Textauswahl kopieren": "Copiar seleção de texto",
    "in Prompt übernehmen": "Inserir no prompt",
    "Auswahl in Prompt übernehmen": "Inserir seleção no prompt",

    # Entities and Fields
    "Mandant": "Cliente",
    "Mandanten": "Clientes",
    "Gegner": "Parte Contrária",
    "Dritte": "Terceiros",
    "Akte": "Processo",
    "Akten": "Processos",
    "Akte:": "Processo:",
    "Akten:": "Processos:",
    "Aktenzeichen": "Número do Processo",
    "Aktenzeichen:": "Número do Processo:",
    "Aktennotiz": "Anotação do Processo",
    "Aktenkonto": "Conta do Processo",
    "Dokument": "Documento",
    "Dokumente": "Documentos",
    "Dokument:": "Documento:",
    "Dokumente:": "Documentos:",
    "Datei": "Arquivo",
    "Dateien": "Arquivos",
    "Datei:": "Arquivo:",
    "Dateien:": "Arquivos:",
    "Ordner": "Pasta",
    "Ordner:": "Pasta:",
    "Benutzer": "Usuário",
    "Benutzer:": "Usuário:",
    "Benutzername": "Nome de Usuário",
    "Benutzername:": "Nome de Usuário:",
    "Passwort": "Senha",
    "Passwort:": "Senha:",
    "Kennwort": "Senha",
    "Kennwort:": "Senha:",
    "root-Passwort:": "Senha de Administrador (root):",
    "Passwort wiederholen:": "Confirmar senha:",
    "Administratorrechte": "Permissões de Administrador",
    "inaktiver Benutzer": "Usuário inativo",
    "Verbindung": "Conexão",
    "Termin": "Audiência / Compromisso",
    "Termine": "Compromissos",
    "Frist": "Prazo",
    "Fristen": "Prazos",
    "Wiedervorlage": "Lembrete",
    "Wiedervorlagen": "Lembretes",
    "Wiedervorlage / Frist": "Lembrete / Prazo",
    "Rechnung": "Fatura",
    "Rechnungen": "Faturas",
    "Zahlung": "Pagamento",
    "Zahlungen": "Pagamentos",
    "Zahlung:": "Pagamento:",
    "Zahlungseingang": "Recebimento",
    "Zahlungsausgang": "Pagamento Efetuado",
    "Honorar": "Honorários",
    "Vergütung": "Honorários",
    "Gericht": "Tribunal",
    "Gerichte": "Tribunais",
    "Beteiligte": "Partes Envolvidas",
    "Beteiligter": "Parte Envolvida",
    "Beteiligtentypen": "Tipos de Partes Envolvidas",
    "Rubrum": "Cabeçalho Processual",
    "Vorlage": "Modelo",
    "Vorlagen": "Modelos",
    "Vorlage:": "Modelo:",
    "Nachname": "Sobrenome",
    "Nachname:": "Sobrenome:",
    "Vorname": "Nome",
    "Vorname:": "Nome:",
    "Straße": "Endereço / Logradouro",
    "Straße:": "Endereço / Logradouro:",
    "PLZ": "CEP",
    "PLZ:": "CEP:",
    "Ort": "Cidade",
    "Ort:": "Cidade:",
    "Telefon": "Telefone",
    "Telefon:": "Telefone:",
    "Mobiltelefon": "Celular",
    "Mobiltelefon:": "Celular:",
    "Telefax": "Fax",
    "Telefax:": "Fax:",
    "E-Mail": "E-mail",
    "E-Mail:": "E-mail:",
    "Webseite": "Site",
    "Notiz": "Nota",
    "Notizen": "Notas",
    "Betreff": "Assunto",
    "Betreff:": "Assunto:",
    "An:": "Para:",
    "Kopie (CC):": "Cópia (CC):",
    "Blindkopie (BCC):": "Cópia Oculta (CCO):",
    "Posteingang": "Caixa de Entrada",
    "Postausgang": "Caixa de Saída",
    "Entwürfe": "Rascunhos",
    "Gesendet": "Enviados",
    "Papierkorb": "Lixeira",
    "Spam": "Spam",
    "Etikett": "Etiqueta",
    "Etiketten": "Etiquetas",
    "Status": "Status",
    "Status:": "Status:",
    "Beschreibung": "Descrição",
    "Beschreibung:": "Descrição:",
    "Datum": "Data",
    "Datum:": "Data:",
    "Uhrzeit": "Hora",
    "Uhrzeit:": "Hora:",
    "Betrag": "Valor",
    "Betrag:": "Valor:",
    "Saldo": "Saldo",
    "Saldo:": "Saldo:",

    # Form / Menu Specific Strings
    "Akte bearbeiten": "Editar processo",
    "gewählte Akte bearbeiten": "Editar processo selecionado",
    "für alle zum Speichern markierten Dateien übernehmen": "Aplicar a todos os arquivos marcados para salvar",
    "zur Akte speichern": "Salvar no processo",
    "Textnachrichten / SMS": "Mensagens de Texto / SMS",
    "Neues Dokument aus Vorlage erstellen und das Ergebnis dieses Dialogs übergeben. \nDie Vorlage benötigt den Platzhalter {{INGO_TEXT}}.": "Criar novo documento a partir de modelo e transferir o resultado deste diálogo.\nO modelo requer o marcador {{INGO_TEXT}}.",
    "Zielakte markieren:": "Selecionar processo de destino:",
    "Rechnungsnummer bei Rechnungserstellung manuell editierbar machen": "Permitir edição manual do número da fatura na emissão",
    "weitere Zeichen als fixe Bestandteile": "Outros caracteres como componentes fixos",
    "Einstellungen Positionsvorlage": "Configurações de modelo de item",
    "Einstellungen testen": "Testar configurações",
    "Ablaufdatum - bei Eintragung wird eine Warnung vor Ablauf erscheinen": "Data de validade - se informada, será exibido aviso prévio",
    "bspw. offene Posten, Aktenhistorien": "ex: contas a receber, histórico de processos",
    "Voice-over-IP - Einstellungen": "Configurações Voice-over-IP",
    "Informationen per Copy & Paste-Assistent übernehmen": "Importar informações via assistente Copiar & Colar",
    "neues Fax senden": "Enviar novo fax",
    "E-Rechnung (HTML)": "Fatura Eletrônica (HTML)",
    "E-Rechnung (XML)": "Fatura Eletrônica (XML)",
    "Bearbeiten der Platzhalterwerte durch Doppelklick möglich": "Edição de valores de marcadores disponível com duplo clique",
    "Erstellen und Öffnen": "Criar e Abrir",
    "alle selektierten Dokumente in ein PDF exportieren": "Exportar todos os documentos selecionados para um PDF",
    "Der hier eingegebene Wert wird den Vorlagenplatzhaltern in diesem Blatt vorangestellt. In der Regel kann die Voreinstellung ohne Änderung übernommen werden.": "O valor aqui informado será prefixado aos marcadores de modelo nesta folha. Geralmente o padrão pode ser mantido sem alterações.",
    "Dokumentetikett auswählen": "Selecionar etiqueta do documento",
    "Ordner auswählen": "Selecionar pasta",
    "Dokumente zusammenführen": "Mesclar documentos",
    "Dokumente sortieren": "Ordenar documentos",
    "Dokumente in der Übersicht per Drag & Drop sortieren": "Ordenar documentos na visualização via arrastar e soltar",
    "Reihenfolge der Dokumente umkehren": "Inverter ordem dos documentos",
    "Zahlungseingang:": "Recebimento:",
    "in dieser Akte duplizieren": "Duplicar neste processo",
    "Karte zur Adresse im Browser öffnen": "Abrir mapa do endereço no navegador",
    "Route zur Adresse im Browser öffnen": "Abrir rota para o endereço no navegador",
    "gewählte Akten löschen": "Excluir processos selecionados",
    "Allgemeine Nachricht": "Mensagem Geral",
    "Testnachricht": "Mensagem de Teste",
    "Nachricht wird nicht qualifiziert signiert": "A mensagem não será assinada de forma qualificada",
    "Beteiligte-Akte": "Partes Envolvidas - Processo",
    "Akte-Beteiligte": "Processo - Partes Envolvidas",
    "Hochladen und Bearbeiten": "Importar e Editar",
    "Passwortschutz:": "Proteção por senha:",
    "Generiert ein neues zufälliges Passwort": "Gera uma nova senha aleatória",
    "OSCI-Nachrichtenansicht": "Visualização de Mensagem Eletrônica",
    "Nachrichten-ID:": "ID da Mensagem:",
    "Datumsauswahl": "Seleção de Data",
    "Adressbuch-Synchronisation": "Sincronização de Contatos",
    "Es werden die Platzhalter des Vorlagensystems unterstützt.\nAktenbezogene Platzhalter (bspw. {{AKTE_ZEICHEN}}) werden nur dann ersetzt,\nwenn der Prompt aus einer Akte heraus verwendet wird.": "Os marcadores do sistema de modelos são suportados.\nMarcadores relacionados a processos (ex: {{AKTE_ZEICHEN}}) serão substituídos apenas\nquando o prompt for utilizado a partir de um processo.",
    "Verschlüsselungspasswort:": "Senha de criptografia:",
    "bei Angabe eines Passwortes wird die Datensicherung verschlüsselt und passwortgeschützt": "Se informada uma senha, o backup será criptografado e protegido por senha",
    "Zielordner:": "Pasta de destino:",
    "Zielordner auf dem Server:": "Pasta de destino no servidor:",
    "für nicht vorhandene Spalten bitte \"-1\" wählen": "Para colunas inexistentes, favor selecionar \"-1\"",
    "Einstellungen beA-Schnittstelle": "Configurações da Integração Judicial",
    "Vorlagen für Wiedervorlagen, Fristen und Termine": "Modelos de Lembretes, Prazos e Audiências",
    "neue Akte erstellen": "Criar novo processo",
    "neues Dokument": "Novo documento",
    "neuer Ordner": "Nova pasta",
    "neuer Ordner...": "Nova pasta...",
    "Ordner löschen": "Excluir pasta",
    "Ordner umbenennen": "Renomear pasta",
    "Unterordner erstellen": "Criar subpasta",
    "in Akte speichern": "Salvar no processo",
    "in Akte speichern...": "Salvar no processo...",
    "in Akte verschieben": "Mover para o processo",
    "in Akte verschieben...": "Mover para o processo...",
    "als PDF zur Akte speichern": "Salvar como PDF no processo",
    "in Zwischenablage kopieren": "Copiar para a área de transferência",
    "lokal speichern": "Salvar localmente",
    "in andere Akte kopieren": "Copiar para outro processo",
    "in andere Akte verschieben": "Mover para outro processo",
    "Erstellungsdatum anpassen": "Ajustar data de criação",
    "farblich hervorheben": "Destacar com cor",
    "erste Farbe": "Primeira cor",
    "zweite Farbe": "Segunda cor",
    "Farbe entfernen": "Remover cor",
    "Favoritendokument an/aus": "Favoritar / Desfavoritar documento",
    "Nachricht senden": "Enviar mensagem",
    "PDF und Konvertierung": "PDF e Conversão",
    "Texterkennung (OCR)": "Reconhecimento de texto (OCR)",
    "als PDF zusammenführen": "Mesclar como PDF",
    "PDF aufteilen": "Dividir PDF",
    "PDF aufteilen ": "Dividir PDF",
    "Suche zurücksetzen": "Limpar pesquisa",
    "neues Dokument aus Vorlage erstellen": "Criar novo documento a partir de modelo",
    "vorhandene Datei hinzuladen": "Importar arquivo existente",
    "Liste nach LibreOffice exportieren": "Exportar lista para LibreOffice",
    "einsehen / bearbeiten": "Visualizar / Editar",
    "Weiterleiten": "Encaminhar",
    "im Browser öffnen": "Abrir no navegador",
    "Scan zur Akte speichern": "Salvar digitalização no processo",
    "Dokumentenvorschau": "Pré-visualização de Documentos",
    "Ereignisvorlagen": "Modelos de Eventos",
    "Belegpositionen (Vorlagen)": "Modelos de Lançamento",
    "Zeiterfassungspositionen (Vorlagen)": "Modelos de Registro de Horas",
    "Buchen: Kontoauszug importieren": "Lançamento: Importar Extrato Bancário",
    "Zahlungen verwalten": "Gerenciar Pagamentos",
    "Import: Gerichtsadressen": "Importar: Endereços de Tribunais",
    "Import / Export: Einstellungen": "Importar / Exportar: Configurações",
    "Export: Akten": "Exportar: Processos",
    "Exportieren von zur Synchronisation markierten Akten": "Exportar processos marcados para sincronização",
    "Akten-Etiketten": "Etiquetas de Processos",
    "Akten-Listenetiketten": "Etiquetas de Listas de Processos",
    "Dokumentordner": "Pastas de Documentos",
    "Eigene Felder (Beteiligte)": "Campos Personalizados (Partes Envolvidas)",
    "zufälliger Desktophintergrund": "Plano de fundo aleatório",
    "Profil aus Zwischenablage importieren": "Importar perfil da área de transferência",
    "j-lawyer.BOX Management Console öffnen": "Abrir Console de Gerenciamento ATRIUM",
    "j-lawyer.BOX suchen": "Pesquisar Servidor ATRIUM",
    "2. App starten und Profile-Dialog öffnen": "2. Iniciar aplicativo e abrir diálogo de perfis",
    "3. Profil durch scannen des QR-Codes übernehmen": "3. Importar perfil escaneando o código QR",
    "beA-Teilnehmer suchen": "Pesquisar participante beA / Tribunal",
    "in Akte speichern (ohne Anhänge)...": "Salvar no processo (sem anexos)...",
    "in Akte speichern (nur Anhänge)...": "Salvar no processo (apenas anexos)...",
    "neue Nachricht schreiben": "Escrever nova mensagem",
    "neue Nachrichten abrufen": "Buscar novas mensagens",
    "Profil auswählen": "Selecionar perfil",
    "Profile": "Perfis",
    "Login": "Login",
    "0 Akten": "0 Processos",
    "0 Akten im Archiv": "0 Processos arquivados",
    "0 Adressbucheinträge": "0 Contatos",
    "0 Dokumente": "0 Documentos",
    "unbearbeitete E-Mails": "E-mails pendentes",
    "Dokument-Etiketten": "Etiquetas de Documentos",
    "Offene Posten": "Contas a Receber (Em Aberto)",
    "Zahlungseingänge": "Pagamentos Recebidos",
    "Zahlungsausgänge": "Pagamentos Efetuados",
    "Kontoauszug (CSV-Datei):": "Extrato Bancário (Arquivo CSV):",
    "Durchsuchen...": "Procurar...",
    "Kontoauszug importieren": "Importar Extrato",
    "Neue Vorlage...": "Novo Modelo...",
    "Neue Vorlage": "Novo Modelo",
    "Vorlage löschen": "Excluir Modelo",
    "Vorlage umbenennen": "Renomear Modelo",
    "Neuer Ordner...": "Nova Pasta...",
    "Neuer Ordner": "Nova Pasta",
    "Seitenbereich (z.B. 1-3, 5):": "Intervalo de páginas (ex: 1-3, 5):",
    "Posteingangsserver (IMAP)": "Servidor de Entrada (IMAP)",
    "Postausgangsserver (SMTP)": "Servidor de Saída (SMTP)",
    "Verbindung verschlüsseln (SSL/TLS)": "Criptografia da conexão (SSL/TLS)",
    "Aktenzeichen-Format": "Formato do Número do Processo",
    "fortlaufende Nummer": "Número sequencial",
    "Jahreszahl (2-stellig)": "Ano (2 dígitos)",
    "Jahreszahl (4-stellig)": "Ano (4 dígitos)",
    "Empfänger (beA):": "Destinatário (beA / Tribunal):",
    "Anhang hinzufügen...": "Adicionar anexo...",
    "Anhang hinzufügen": "Adicionar anexo",
    "Rechnungsempfänger": "Destinatário da fatura",
    "Rechnungserstellung": "Emissão de fatura",
    "Leistungszeitraum": "Período de prestação de serviços",
    "Rechnungsbetrag": "Valor total da fatura",
    "Rechnungsposition": "Item da fatura",
    "Rechnungspositionen": "Itens da fatura",
    "Postausgang nicht leer": "Caixa de Saída com Mensagens Pendentes",
    "Entwurf speichern": "Salvar Rascunho",
    "Dokument löschen": "Excluir Documento",
    "Akte archivieren": "Arquivar Processo",
    "Adresse speichern": "Salvar Contato",
    "Passwort ändern": "Alterar Senha",
    "Passwort festlegen": "Definir Senha",
    "Dokument umbenennen": "Renomear Documento",
    "Dokumente löschen": "Excluir Documentos",
    "Zahlungen verbuchen": "Lançar Pagamentos",
    "Ordner anlegen": "Criar Pasta",
    "Benutzer löschen": "Excluir Usuário",
    "Profil anlegen": "Criar Perfil",
    "Profil löschen": "Excluir Perfil",
    "Profil umbenennen": "Renomear Perfil",
    "% Speichernutzung": "% Uso de Memória",
    "00123/22 eine Aktenbezeichnung": "00123/22 Descrição do processo",
    "2. Passwort setzen / zurücksetzen": "2. Definir / redefinir senha",
    "3. Passwort setzen und in die Einstellungen übernehmen": "3. Definir senha e aplicar às configurações",
    "<Rechnungsadresse>": "<Endereço de Faturamento>",
    "suchen (Adressbuch)": "Pesquisar (Contatos)",
    "suchen (beA-Verzeichnis)": "Pesquisar (Tribunal)",
    "neue beA-Nachricht": "Nova mensagem judicial",
    "in \"Entwürfe\" speichern und später signieren/senden": "Salvar em \"Rascunhos\" e assinar/enviar mais tarde",
    "als Dokument speichern": "Salvar como documento",
    "Gesendete Nachricht als Dokument zur Akte speichern": "Salvar mensagem enviada como documento no processo",
    "Keine auswählen": "Nenhum selecionado",
    "Nachname, Vorname (Username)": "Sobrenome, Nome (Usuário)",
    "PDF anzeigen / speichern": "Visualizar / salvar PDF",
    "Nachrichtenjournal erneut aus dem Postfach laden": "Recarregar histórico de mensagens da caixa de correio",
    "eEB zurückweisen": "Recusar aviso de recebimento eletrônico",
    "elektronisches Empfangsbekenntnis zurückweisen": "Recusar aviso de recebimento eletrônico",
    "Nachricht als PDF anzeigen / drucken": "Visualizar / imprimir mensagem como PDF",
    "weitere": "mais",
    "Nachricht": "Mensagem",
    "in Akte...": "No processo...",
    "Menge der angezeigten Nachrichten beschränken": "Limitar quantidade de mensagens exibidas",
    "Hinweis: temporäre Dateien": "Aviso: arquivos temporários",
    "verschiebt die Nachricht nach Zuordnung in den Ordner \"in Akte importiert\"": "Move a mensagem após vinculação para a pasta \"importada no processo\"",
}

print(f"Loaded {len(FORM_TRANSLATIONS)} translations")
