window.title=C\u00f3pia de Seguran\u00e7a Autom\u00e1tica (Backup)
msg.error.backuperror=N\u00e3o foi poss\u00edvel iniciar o backup: {0}
msg.backupstarted.title=Backup
msg.backupstarted=O backup foi iniciado e est\u00e1 em execu\u00e7\u00e3o em segundo plano.
msg.port.invalid.title=Backup
msg.port.invalid=A porta do banco de dados \u00e9 inv\u00e1lida - valores permitidos de 1 a 65535.
label.dbport=Porta do BD:
button.backupnow=Executar backup agora
label.dbpassword=Senha do BD:
label.dbuser=Usu\u00e1rio do BD:
button.save=Salvar
button.close=Fechar
label.pointintime=Hor\u00e1rio:
label.oclock=horas
chk.sunday=Dom
chk.saturday=S\u00e1b
chk.friday=Sex
chk.thursday=Qui
chk.wednesday=Qua
chk.tuesday=Ter
chk.monday=Seg
label.weekdays=Dias da semana:
option.off=desativado
option.on=ativado
label.automatedbackup=Backup autom\u00e1tico:
label.helptextsync=<html>C\u00f3pias de seguran\u00e7a devem ser arquivadas externamente para preven\u00e7\u00e3o de falhas de hardware.<br/> Voc\u00ea pode configurar a sincroniza\u00e7\u00e3o dos backups para os seguintes destinos:<br/><ul><li>Pastas compartilhadas Windows / SMB</li><li>Pastas FTP</li><li>Pastas SFTP (SSH)</li></ul></html>
label.helptext=<html>Com o usu\u00e1rio e senha do banco de dados salvos, voc\u00ea pode solicitar um backup imediato.<br/> O backup ter\u00e1 in\u00edcio imediato e sua dura\u00e7\u00e3o depender\u00e1 do volume de dados. Se voc\u00ea tiver configurado um e-mail em &quot;Administra\u00e7\u00e3o - Caixa Postal do Sistema&quot;, receber\u00e1 um resumo ap\u00f3s a conclus\u00e3o.</html>
label.helptextexport=<html>Se informar um diret\u00f3rio acess\u00edvel no servidor, cada backup tamb\u00e9m gerar\u00e1 uma exporta\u00e7\u00e3o em HTML naveg\u00e1vel. Assim, em caso de emerg\u00eancia ou indisponibilidade, ser\u00e1 poss\u00edvel acessar os dados diretamente pelo navegador.</html>
