button.close=Fechar
customfield3.default=Campo Personalizado 3
customfield2.default=Campo Personalizado 2
customfield1.default=Campo Personalizado 1
label.restartrequired=Requer reinicializa\u00e7\u00e3o do cliente BR-LAWYER
customfield3.name=Nome para Campo Personalizado 3:
customfield2.name=Nome para Campo Personalizado 2:
customfield1.name=Nome para Campo Personalizado 1:
button.save=Salvar
