# BR-LAWYER - Localiza\u00e7\u00e3o em Portugu\u00eas do Brasil (pt-BR)

followup.nodescription=(sem descri\u00e7\u00e3o)
dialog.error.saving=Erro ao salvar: {0}
dialog.confirm.setdone=Marcar o prazo "{0}" como cumprido / conclu\u00eddo?
dialog.error.loadingeditor=Erro ao carregar o editor: {0}
dialog.error.loadingcase=Erro ao carregar o processo: {0}
label.followup=Acompanhamento / Lembrete
caption.responsible=respons\u00e1vel
caption.case=Processo
caption.due=vencimento
caption.followup=Acompanhamento
caption.respite=PRAZO PROCESSUAL
msg.error=Erro
dialog.confirm.setdone.title=Prazo Conclu\u00eddo?
dialog.confirm.setdone.multiple=Marcar {0} prazos como cumpridos / conclu\u00eddos?\n{1}
dialog.confirm.setdone.multiple.title=Prazos Conclu\u00eddos?
dialog.confirm.lastopen=\u00daltimo compromisso pendente do processo {0} {1}. Deseja fechar mesmo assim?
dialog.confirm.lastopen.title=Aviso
dialog.confirm.delete.title=Excluir Prazo?
dialog.confirm.delete.title.multiple=Excluir Compromissos / Prazos?
dialog.confirm.delete.respite=Voc\u00ea est\u00e1 prestes a excluir o seguinte PRAZO PROCESSUAL:\n{0}\nPrazos exclu\u00eddos n\u00e3o ser\u00e3o mais monitorados nem emitir\u00e3o alertas!\nConfirma a exclus\u00e3o?
dialog.confirm.delete.respite.multiple=Voc\u00ea est\u00e1 prestes a excluir {0} compromissos, incluindo os seguintes PRAZOS:\n{1}Prazos exclu\u00eddos n\u00e3o ser\u00e3o mais monitorados!\nConfirma a exclus\u00e3o?
dialog.confirm.delete.respite.open=(PENDENTE!)
dialog.confirm.delete.yes=Sim
dialog.confirm.delete.no=N\u00e3o
