# BR-LAWYER - EditorsRegistry Localiza\u00e7\u00e3o pt-BR

status.ready=pronto
status.news.moreinfo=Clique para mais informa\u00e7\u00f5es
status.news.tooltip=Not\u00edcias do projeto BR-LAWYER dispon\u00edveis
status.news.title=Not\u00edcias do BR-LAWYER
launch.browser.error=N\u00e3o foi poss\u00edvel abrir o navegador de internet automaticamente. As informa\u00e7\u00f5es est\u00e3o dispon\u00edveis em {0}
status.updatesfound.moreinfo=Clique para mais informa\u00e7\u00f5es
status.updatesfound.installed=instalado
status.updatesfound.fromdate=de
status.updatesfound.newversion=nova vers\u00e3o
status.updatesfound.text=Atualiza\u00e7\u00f5es do BR-LAWYER dispon\u00edveis:
status.updatesfound=Atualiza\u00e7\u00e3o(\u00f5es) dispon\u00edvel(is)
monitoring.okay=Nenhum problema de sistema detectado.<br/>Clique para mais informa\u00e7\u00f5es
monitoring.warn=Existem avisos do sistema.<br/>Clique para mais informa\u00e7\u00f5es
monitoring.error=Existem erros no sistema.<br/>Clique para mais informa\u00e7\u00f5es
caption.failedfaxes=Um ou mais despachos n\u00e3o puderam ser enviados.
status.unreadmails=\ e-mail(s) n\u00e3o lido(s)
status.scansfound=\ digitaliza\u00e7\u00e3o(\u00f5es) encontrada(s)
dialog.savebeforeexit.title=Salvar altera\u00e7\u00f5es
dialog.savebeforeexit=Deseja salvar os dados antes de sair?
