launch.browser=Abrir Navegador...
button.copy.tooltip=Copiar endere\u00e7o para a \u00e1rea de transfer\u00eancia
button.copy=Copiar Link
button.close=Fechar
launch.browser.hint=Copie o endere\u00e7o abaixo e cole no seu navegador de internet.
launch.browser.failed=N\u00e3o foi poss\u00edvel abrir o navegador automaticamente.
