# BR-LAWYER - Localiza\u00e7\u00e3o em Portugu\u00eas do Brasil (pt-BR)

role=Papel do contato:
error.loadingeditor=Erro ao carregar o editor: {0}
error.loadingcase=Erro ao carregar o processo: {0}
label.case.name=Excluir digitaliza\u00e7\u00e3o(\u00f5es)
dialog.error=Erro
role.client=Cliente / Requerente
role.opponent=Parte Contr\u00e1ria / Requerido
role.third=Terceiro Interessado / Outro
