# BR-LAWYER - Localiza\u00e7\u00e3o em Portugu\u00eas do Brasil (pt-BR)

error.jms.systemmonitoring=Erro ao registrar para mensagens de monitoramento do sistema: {0}
error.launchsettings=N\u00e3o foi poss\u00edvel abrir o di\u00e1logo de configura\u00e7\u00f5es: 
error.launchimport=N\u00e3o foi poss\u00edvel abrir o di\u00e1logo de importa\u00e7\u00e3o: 
error.launchconsole=N\u00e3o foi poss\u00edvel abrir o console do administrador: 
error.savingsettings=Erro ao salvar as configura\u00e7\u00f5es: 
error.loadingeditor=Erro ao carregar o m\u00f3dulo: 
dialog.title.casecustomfields=Processo: R\u00f3tulos para campos personalizados
dialog.title.addresscustomfields=Contato: R\u00f3tulos para campos personalizados
dialog.title.addresstags=Etiquetas
dialog.title.titles=T\u00edtulos
dialog.title.casetags=Etiquetas
dlg.title.subjectfields=Ramos do Direito / Assuntos
dialog.title.about=Sobre o BR-LAWYER...
msg.title.hint=Aviso
msg.title.error=Erro
msg.adminrequired=Privil\u00e9gios de Administrador s\u00e3o necess\u00e1rios para executar esta a\u00e7\u00e3o.
dialog.title.salutations=Formas de Tratamento
dialog.title.importbanks=Importa\u00e7\u00e3o de Bancos
dialog.title.importzipcodes=Importa\u00e7\u00e3o de CEPs
dialog.title.dictatesign=Sigla de Respons\u00e1vel
dialog.title.reviews=Motivos de Acompanhamento e Prazos
menu.?.about=Sobre...
menu.?.onlinehelp=Ajuda Online
menu.?=?
menu.settings.monitoring=Monitoramento do Servidor
menu.settings.adminconsole=Console do Administrador
menu.settings.backup=C\u00f3pia de Seguran\u00e7a (Backup)
menu.settings.voip=Telefonia / VoIP
menu.settings.profile=Perfil do Escrit\u00f3rio
menu.settings.users=Gest\u00e3o de Usu\u00e1rios
menu.settings.themes=Temas
menu.settings.fontsize=Tamanho da Fonte
menu.settings.documents.3rdpartyapps=Aplicativos Externos
menu.settings.documents.search=Busca Textual de Documentos
menu.settings.documents.scanner=Integra\u00e7\u00e3o com Scanner
menu.settings.documents=M\u00f3dulo 'Documentos'
menu.settings.cases.customfields=Campos Personalizados
menu.settings.cases.tags=Etiquetas
menu.settings.cases.subjectfields=Ramos do Direito / Assuntos
menu.settings.cases.dictatesigns=Siglas de Respons\u00e1veis
menu.settings.cases=M\u00f3dulo 'Processos'
menu.settings.addresses.customfields=Campos Personalizados
menu.settings.addresses.tags=Etiquetas de Contatos
menu.settings.addresses.titles=T\u00edtulos (Cabe\u00e7alho)
menu.settings.addresses.complimentaryclose=F\u00f3rmulas de Fechamento / Cumprimentos
menu.settings.addresses.salutations=Tratamentos / Voca\u00e7\u00f5es
menu.settings.addresses=M\u00f3dulo 'Contatos'
menu.settings=Configura\u00e7\u00f5es
menu.file.exit=Sair
menu.file.import.addresses=Importar Contatos
menu.file.import.zipcodes=Importar Base de CEPs
menu.file.import.banks=Importar Base de Bancos
menu.file=Arquivo
status.ready=Pronto
title=BR-LAWYER Client
menu.settings.userprofile=Perfil do Usu\u00e1rio
menu.settings.cases.numbering=Esquema de Numera\u00e7\u00e3o Processual (CNJ)
menu.?.documentmonitor=Monitor de Documentos
dialog.title.complimentaryclose=Cumprimentos Finais
msg.sysadminrequired=Privil\u00e9gios de Administrador do Sistema s\u00e3o necess\u00e1rios para executar esta a\u00e7\u00e3o.
