# BR-LAWYER - Modules Localiza\u00e7\u00e3o pt-BR

mod.mydesktop=Painel Principal
mod.cases=Processos
mod.cases.new=novo
mod.cases.view=visualizar
mod.cases.edit=pesquisar
mod.contacts=Contatos
mod.contacts.new=novo
mod.contacts.view=visualizar
mod.contacts.edit=pesquisar
mod.fup=Prazos, Audi\u00eancias e Acompanhamentos
mod.fup.byduedate=por vencimento
mod.fup.find=pesquisar
mod.comm=Comunica\u00e7\u00f5es
mod.comm.inbox=Caixa de Entrada de E-mails
mod.comm.templates=Modelos
mod.comm.fax=Status de Despacho
mod.docs=Documentos
mod.docs.master=Modelos Mestres
mod.docs.templates=Modelos
mod.docs.scans=Digitaliza\u00e7\u00f5es
mod.docs.search=Busca Textual
mod.history=Hist\u00f3rico
mod.history.my=Minha Linha do Tempo
mod.history.all=Hist\u00f3rico Geral
mod.fup.missing=pend\u00eancias
mod.comm.bea=Publica\u00e7\u00f5es e Tribunais
mod.knowledge=Base de Conhecimento
mod.knowledge.ug=
mod.comm.massmail=Mala Direta
mod.workflow.br=Workflow Jur\u00eddico
